--Auhtor Constraints
CREATE TABLE Authors(
	AuthorId INT NOT NULL,
	FirstName VARCHAR(20),
	LastName VARCHAR(20)
);

ALTER TABLE Authors
ADD CONSTRAINT PK_Author PRIMARY KEY (AuthorId)

ALTER TABLE Authors
ALTER COLUMN FirstName VARCHAR(20) NOT NULL

ALTER TABLE Authors
ALTER COLUMN LastName VARCHAR(20) NOT NULL

--Book Constraints
CREATE TABLE Books(
	BookId INT NOT NULL,
	Title VARCHAR(20),
	AuthorId INT,
	PublishedYear INT
);

ALTER TABLE Books
ADD CONSTRAINT PK_Books_1 PRIMARY KEY (BookId)

ALTER TABLE Books
ALTER COLUMN Title VARCHAR(20) NOT NULL

ALTER TABLE Books
ADD CONSTRAINT FK_Books FOREIGN KEY (AuthorId) REFERENCES Authors(AuthorId) 

ALTER TABLE Books
ADD CONSTRAINT Check_Year CHECK (PublishedYear BETWEEN 1500 AND YEAR(GETDATE()))

ALTER TABLE Books ADD CONSTRAINT Unique_Name UNIQUE (Title); 

--Member Constraint
CREATE TABLE Members_1(
	MemberId INT NOT NULL,
	FirstName VARCHAR(20),
	LastName VARCHAR(20),
	Email VARCHAR(20)
);

ALTER TABLE Members_1
ADD CONSTRAINT M_Author PRIMARY KEY (MemberId)

ALTER TABLE Members_1
ALTER COLUMN FirstName VARCHAR(20) NOT NULL

ALTER TABLE Members_1
ALTER COLUMN LastName VARCHAR(20) NOT NULL

ALTER TABLE Members_1
ALTER COLUMN Email VARCHAR(20) NOT NULL

ALTER TABLE Members_1
ADD CONSTRAINT Unique_Email UNIQUE (Email);

--Loan Constraint
CREATE TABLE Loans_1(
	LoanId INT NOT NULL,
	BookId INT,
	MemberId INT,
	LoanDate DATE,
	ReturnDate DATE
)

ALTER TABLE Loans_1
ADD CONSTRAINT PK_Loans PRIMARY KEY (LoanId)

ALTER TABLE Loans_1
ADD CONSTRAINT FK_Loans_book FOREIGN KEY (BookId) REFERENCES Books(BookId) 

ALTER TABLE Loans_1
ADD CONSTRAINT FK_Loans_member FOREIGN KEY (MemberId) REFERENCES Members(MemberId) 

ALTER TABLE Loans_1
ALTER COLUMN LoanDate DATE NOT NULL

ALTER TABLE Loans_1
ADD CONSTRAINT Check_Return CHECK (ReturnDate IS NULL OR ReturnDate > LoanDate)